// <auto-generated />
namespace Hotel.Repositorio.EF
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cria_coluna_data_casamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cria_coluna_data_casamento));
        
        string IMigrationMetadata.Id
        {
            get { return "202210042200547_cria_coluna_data_casamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
